### ISSUE TITLE
Add functionality to run data files individually

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#48]
The current Java GudrunGUI offers functionality for running data files individually whilst running gudrun_dcs. This is likely done by splitting one Sample with N data files into N samples each with a singular data file.

Should be fairly easy to implement - can be implemented as a class similarly to the TweakFactorIterator  #21 and WavelengthSubtractionIterator #22. A possible name could be `RunIndividualFiles`.

Although - not sure how we should name the samples? We surely cannot have them all share the original name, since the output files of gudrun_dcs would keep getting overwritten?

**Comment by jswift-stfc** [comment]
Coming back to this, @trisyoungs - how should we handle the multiple samples created - should they all be named the same?

**Comment by trisyoungs** [comment]
Since `gudrun_dcs` doesn't care about sample names (these are a human construction, after all) when running data files individually for a given sample GudrunGUI writes out a `gudrun_dcs.dat` file with multiple samples of the same name in it, each with only one data file. GudPy can mimic this behaviour when it writes out the input file in the same way.

Thinking of the bigger picture for a moment, the ability to run files individually is a basic version of "data file manipulation", lets call it, that would be extended by the work you're doing with h5py. Grouping these options together later in the GUI when the time is right would be sensible.
